

def my_task():
    raise Exception('some network error, try again')
